server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    hikari:
      connection-timeout: 2000
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
    url: ##
    username: ##
    password: ##
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  main:
    allow-bean-definition-overriding: true
  cloud:
    gcp:
      core:
        enabled: true
      config:
        project-id: central-splice-375306
        credentials:
          location: classpath:gcp-account-file.json
        enabled: true
      pubsub:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html